[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
nom = "7.1.3"
rstest = "0.18.2"
anyhow = "1.0.75"
itertools = "0.12.0"
rayon = "1.8.0"
dhat = "0.3.2"
rstest_reuse = "0.6.0"
cached = "0.46.1"

[profile.release]
debug = 1
